# Generated by Django 5.1.1 on 2024-10-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviones_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviones',
            old_name='noasajeros',
            new_name='npasajeros',
        ),
    ]
